# Generated by Django 4.2.6 on 2023-11-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaServicio',
            fields=[
                ('ID_AGEN_SERVICIO', models.IntegerField(primary_key=True, serialize=False)),
                ('FECHA_AGENDADA', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_CLIENTE', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('ID_COMPRA', models.IntegerField(primary_key=True, serialize=False)),
                ('TOTAL', models.IntegerField()),
                ('TIPO_COMPRA', models.CharField(max_length=20)),
                ('NRO_BOLETA', models.CharField(max_length=20, null=True)),
                ('NRO_FACTURA', models.CharField(max_length=20, null=True)),
                ('ID_AGEN_SERVICIO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mecanico.agendaservicio')),
                ('ID_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID_PROVEEDOR', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_PROV', models.CharField(max_length=50)),
                ('DIRECCION', models.CharField(max_length=100)),
                ('CORREO', models.EmailField(max_length=50)),
                ('NRO_TELEFONO', models.CharField(max_length=20)),
                ('RUBRO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('ID_SERVICIO', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_SERVICIO', models.CharField(max_length=100)),
                ('DESCRIPCION', models.CharField(max_length=300)),
                ('PRECIO', models.IntegerField()),
                ('IMAGEN', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('ID_TIPO', models.IntegerField(primary_key=True, serialize=False)),
                ('DESC_TIPO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RUN', models.IntegerField(primary_key=True, serialize=False)),
                ('DV', models.CharField(max_length=1)),
                ('PNOMBRE', models.CharField(max_length=100)),
                ('SNOMBRE', models.CharField(max_length=100)),
                ('APPATERNO', models.CharField(max_length=100)),
                ('APMATERNO', models.CharField(max_length=100)),
                ('DIRECCION', models.CharField(max_length=300)),
                ('NOM_USUARIO', models.CharField(max_length=100, unique=True)),
                ('CONTRASENA', models.CharField(max_length=100)),
                ('CORREO', models.EmailField(max_length=200)),
                ('NRO_TELEFONICO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_PRODUCTO', models.IntegerField(primary_key=True, serialize=False)),
                ('NOM_PRODUCTO', models.CharField(max_length=100)),
                ('DESCRIPCION', models.CharField(max_length=300)),
                ('PRECIO', models.IntegerField()),
                ('IMAGEN', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('ID_PROVEEDOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ID_PEDIDO', models.IntegerField(primary_key=True, serialize=False)),
                ('DIRECCION', models.CharField(max_length=100)),
                ('ESTADO', models.CharField(max_length=50)),
                ('ID_COMPRA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('ID_INFORME', models.IntegerField(primary_key=True, serialize=False)),
                ('FECHA', models.DateField()),
                ('ID_COMPRA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_EMPLEADO', models.IntegerField(primary_key=True, serialize=False)),
                ('HORAS_TRABAJO', models.IntegerField()),
                ('FEC_CONTRATACION', models.DateTimeField()),
                ('ID_SERVICIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.servicio')),
                ('RUN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.usuario')),
                ('TIPO_EMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.tipoempleado')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='ID_EMPLEADO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.empleado'),
        ),
        migrations.AddField(
            model_name='compra',
            name='ID_PRODUCTO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mecanico.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='ID_SERVICIO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mecanico.servicio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='RUN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.usuario'),
        ),
        migrations.AddField(
            model_name='agendaservicio',
            name='ID_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.cliente'),
        ),
        migrations.AddField(
            model_name='agendaservicio',
            name='ID_EMPLEADO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.empleado'),
        ),
        migrations.AddField(
            model_name='agendaservicio',
            name='ID_SERVICIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.servicio'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('ID_ADMINISTRADOR', models.IntegerField(primary_key=True, serialize=False)),
                ('RUN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanico.usuario')),
            ],
        ),
    ]
