# Generated by Django 4.2.6 on 2023-11-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casino', '0002_alter_bebida_descripcion_alter_comida_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BEBIDA',
        ),
        migrations.DeleteModel(
            name='COMIDA',
        ),
    ]
