# Generated by Django 4.2.1 on 2023-07-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='nombre',
            new_name='nombre_ciudad',
        ),
    ]
